BEGIN TRANSACTION;

-- reuse stg_user table where phone has changed for 200 customers
INSERT INTO INSTACART.STG_USER (USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE, CITY, STATE, START_TS)
SELECT USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE+1 AS PHONE, 'Manhattan','NY', CURRENT_TIMESTAMP
FROM INSTACART.DIM_USER LIMIT 200;

-- address has changed for 200 users
INSERT INTO INSTACART.STG_USER (USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE, CITY, STATE, START_TS)
SELECT USER_ID, FIRST_NM, LAST_NM, ADDRESS+' Unit '+ CAST(CAST(RANDOM() * 100 AS INT) AS CHAR) AS ADDRESS, PHONE, 'Manhattan','NY', CURRENT_TIMESTAMP
FROM INSTACART.DIM_USER WHERE USER_ID NOT IN (SELECT USER_ID FROM INSTACART.STG_USER) LIMIT 200;

-- name has changed for 200 users
INSERT INTO INSTACART.STG_USER (USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE, CITY, STATE, START_TS)
SELECT USER_ID, FIRST_NM, 'Mc'+LAST_NM, ADDRESS, PHONE, 'Manhattan','NY', CURRENT_TIMESTAMP
FROM INSTACART.DIM_USER WHERE USER_ID NOT IN (SELECT USER_ID FROM INSTACART.STG_USER) LIMIT 200;


-- also let's add three completely new users
INSERT INTO INSTACART.STG_USER (USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE, CITY, STATE, START_TS) 
VALUES (206210, 'Abc', 'Xyz', '1 Main Street', 6843521148, 'Manhattan','NY', CURRENT_TIMESTAMP);

INSERT INTO INSTACART.STG_USER (USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE, CITY, STATE, START_TS)
VALUES (206211, 'Def', 'Ghi', '2 Cross Street', 6843521149, 'Manhattan','NY', CURRENT_TIMESTAMP );

INSERT INTO INSTACART.STG_USER (USER_ID, FIRST_NM, LAST_NM, ADDRESS, PHONE, CITY, STATE, START_TS)
VALUES (206212, 'Jkkl', 'Mno', '3 Side Street', 6843521150,  'Manhattan','NY', CURRENT_TIMESTAMP );


UPDATE INSTACART.STG_USER 
SET TRACK_HASH = FNV_HASH(ADDRESS+PHONE)
WHERE TRACK_HASH IS NULL;

COMMIT TRANSACTION;

